export const EMAIL = 'gustavo.o.silva556@gmail.com';
export const LINKEDIN = 'https://www.linkedin.com/in/gustavo-oliveira-5386b62a0/';
export const CV_URL = '/assets/CV_Gustavo_Oliveira.pdf';

export const NAV = [
  { href: '#capa', label: 'Início' },
  { href: '#competencias', label: 'Competências' },
  { href: '#projetos', label: 'Projetos' },
  { href: '#certificados', label: 'Certificados' },
  { href: '#contato', label: 'Contato' },
];

export const SKILLS = [
  { name: 'Análise de Dados',           source: 'COMUNICAÇÃO', note: 'Fundamentar decisões de comunicação com evidências, não com intuição.' },
  { name: 'Python / NumPy',             source: 'EMAp',        note: 'Automatizar o trabalho pesado para focar no que a máquina não resolve: a narrativa.' },
  { name: 'Estatística Aplicada',       source: 'EMAp',        note: 'Tornar a inferência uma aliada da estratégia — não só da academia.' },
  { name: 'Storytelling com Dados',     source: 'COMUNICAÇÃO', note: 'Traduzir números em narrativa com intenção editorial.' },
  { name: 'Estratégia de Comunicação',  source: 'COMUNICAÇÃO', note: 'Conectar o que os dados revelam às mensagens que marcas precisam transmitir.' },
  { name: 'Engenharia de IA',           source: 'Projetos',    note: 'Ampliar produção e análise sem abrir mão de voz e identidade autoral.' },
  { name: 'DSPy / LLM Pipelines',       source: 'Projetos',    note: 'Construir fluxos de IA que produzem conteúdo com consistência e escala estratégica.' },
  { name: 'Análise Exploratória (EDA)', source: 'COMUNICAÇÃO', note: 'Revelar padrões culturais que os dashboards convencionais não conseguem enxergar.' },
];

export const TAGS = [
  'EDA', 'DSPy', 'Docling', 'Pydantic', 'Claude API', 'Engenharia de IA',
  'Langchain', 'Agno', 'Storytelling', 'Estratégia Digital', 'Análise Comunicacional',
];

export const PROJECTS = [
  {
    id: 4,
    num: '01',
    category: 'Engenharia de Dados & IA',
    date: '2025',
    title: 'Extração Estruturada de Documentos de Segurança Pública',
    challenge: 'Transformar centenas de PDFs brutos com estruturas heterogêneas em um JSON consistente, facilitando análises quantitativas e qualitativas em outras ferramentas.',
    tools: ['Python', 'DSPy', 'PyMuPDF', 'Regex', 'Fine-tuning', 'Fuzzy Matching'],
    solution: 'Pipeline em etapas: extração de texto com PyMuPDF, regex para identificar seções e itens com padrões previsíveis, limpeza, modelo de IA otimizado para a extração específica, fuzzy string matching para resolver ligações entre documentos e um self-correction loop que reprocessa saídas inconsistentes.',
    deliverables: ['Pipeline de coleta com altíssima acurácia', 'JSON estruturado e reaproveitável', 'CSV limpo pronto para análise'],
    discipline: 'Consultoria contratada · Setor público de segurança',
    role: 'Analista contratado: desenho do pipeline, prompt engineering com DSPy, fine-tuning do modelo de extração e validação dos JSONs.',
    impact: 'Documentos antes inacessíveis a métodos quantitativos passaram a alimentar análises cruzadas em outras ferramentas. O loop de self-correction tornou a extração estável mesmo diante das variações estruturais entre PDFs.',
    confidential: true,
  },
  {
    id: 1,
    num: '02',
    category: 'Analytics & IA Generativa',
    date: '2025',
    title: 'Analytics API · Relatórios de Marketing com IA',
    challenge: 'Automatizar a leitura de dados de GA4 e Search Console com clusterização e relatórios narrativos que um time de marketing realmente consiga acionar.',
    tools: ['FastAPI', 'Agno', 'GPT-4o-mini', 'DuckDB', 'scikit-learn', 'Pydantic'],
    solution: 'API REST com 13 endpoints que cruza tráfego, engajamento e conversões. K-Means segmenta canais, keywords e páginas; um agente Agno + GPT-4o-mini transforma os clusters em relatório com sumário executivo, 5 seções analíticas e 8–10 recomendações priorizadas.',
    deliverables: ['API em produção (Render)', 'Simulador de dados realistas (3.668 registros)', 'Documentação para frontend'],
    discipline: 'A2 · FGV · Projeto acadêmico',
    role: 'Arquitetura da API, pipelines de ML, prompt design do agente, deploy.',
    impact: 'Geração de relatório completo em ~80s a custo de ~$0.001 por execução. Sistema vivo em produção no Render.',
    repoUrl: 'https://github.com/GuOliv2306/trabalho_A2',
    liveUrl: 'https://siteup.onrender.com/docs',
  },
  {
    id: 2,
    num: '03',
    category: 'IA Conversacional',
    date: '2024',
    title: 'Oráculo · Chat sobre Documentos & Vídeos',
    challenge: 'Permitir conversar com qualquer fonte — um PDF denso, um vídeo de YouTube, um site, uma planilha — sem precisar processá-la manualmente.',
    tools: ['Streamlit', 'Python', 'OpenAI', 'Groq', 'PDFs', 'YouTube'],
    solution: 'Interface em Streamlit que ingere arquivos (PDF, TXT, CSV) ou links (site, YouTube), formata o conteúdo como system message e abre um chat interativo. Provedor (OpenAI ou Groq) e modelo são selecionáveis em tempo de carga.',
    deliverables: ['App público (GustaBot) no Streamlit Cloud', 'Pipeline modular de ingestão', 'Interface multi-formato'],
    discipline: 'Projeto independente',
    role: 'Arquitetura, integração com APIs de LLM, UX da interface.',
    impact: 'Aplicação publicada e funcional — testes feitos com PDFs longos e transcrições de vídeo.',
    repoUrl: 'https://github.com/GuOliv2306/Project_oraculo',
    liveUrl: 'https://gustabot.streamlit.app/',
  },
  {
    id: 3,
    num: '04',
    category: 'Análise de Consumidor',
    date: '2024',
    title: 'Avaliações de Consumidores · Insights via IA',
    challenge: 'Transformar centenas de avaliações brutas de produtos em insights acionáveis sem perder o sinal qualitativo dentro do ruído de comentários.',
    tools: ['Python', 'OpenAI API', 'Pandas', 'Excel/JSON'],
    solution: 'Pipeline em quatro etapas: extração das avaliações de produtos, limpeza e normalização, envio estruturado para a OpenAI API e consolidação dos insights em tabela final pronta para análise comunicacional.',
    deliverables: ['Pipeline reproduzível em Python', 'Dataset limpo (JSON)', 'Tabela final com insights'],
    discipline: 'Projeto final · FGV',
    role: 'Pipeline completo: extração, limpeza, prompt design e consolidação.',
    impact: 'Tempo de leitura manual de avaliações reduzido a uma execução de script com saída interpretada.',
    repoUrl: 'https://github.com/GuOliv2306/Projeto-Final-Analise-de-Avaliacoes-de-Consumidores',
  },
];

export const CERTS = [
  {
    id: 'agentes-agno',
    category: 'IA & AGENTES',
    year: '2025',
    title: 'Criando Agentes com Agno',
    badge: 'ASIMOV ACADEMY',
    full: 'Criando Agentes com Agno',
    issuer: 'Asimov Academy',
    hours: '14h',
    credential: 'c449192d-2c5a-4f28-8db5-0e93399b5156',
    desc: 'Construção e deploy de agentes autônomos com o framework Agno. Cobre arquitetura de agentes, orquestração com LLMs e publicação em produção — base para os pipelines de IA que uso hoje em projetos próprios.',
    skills: ['Agno', 'Python', 'LLM Agents', 'Deploy'],
    verifyUrl: 'https://hub.asimov.academy/validar-certificado/c449192d-2c5a-4f28-8db5-0e93399b5156/',
  },
  {
    id: 'engenharia-ia',
    category: 'IA & FOUNDATION MODELS',
    year: '2025',
    title: 'Engenharia de IA',
    badge: 'ESTUDO PRÓPRIO · O’REILLY',
    full: 'AI Engineering · Chip Huyen',
    issuer: 'Estudo independente · livro de Chip Huyen (O’Reilly)',
    hours: 'Em curso',
    credential: 'self-study-ai-engineering',
    desc: 'Leitura aplicada do livro AI Engineering — fundamentos de aplicações com foundation models: avaliação, RAG, fine-tuning leve, prompt engineering, custo e latência. Estudo conduzido em paralelo aos projetos próprios.',
    skills: ['Foundation Models', 'RAG', 'Avaliação LLM', 'Prompting'],
    verifyUrl: 'https://www.oreilly.com/library/view/ai-engineering/9781098166298/',
  },
  {
    id: 'matematica-dados',
    category: 'MATEMÁTICA',
    year: '2025',
    title: 'Matemática para Análise de Dados',
    badge: 'ASIMOV ACADEMY',
    full: 'Matemática para Análise de Dados',
    issuer: 'Asimov Academy',
    hours: '7h',
    credential: '3fd894f6-3b5a-46d8-a2d8-07848ae6fa15',
    desc: 'Revisão aplicada de cálculo, álgebra linear, probabilidade e estatística com foco em análise de dados. Ferramental quantitativo que sustenta leituras com rigor e não só com narrativa.',
    skills: ['Cálculo', 'Álgebra Linear', 'Probabilidade', 'Estatística'],
    verifyUrl: 'https://hub.asimov.academy/validar-certificado/3fd894f6-3b5a-46d8-a2d8-07848ae6fa15/',
  },
  {
    id: 'usp-probabilidade',
    category: 'ESTATÍSTICA',
    year: '2026',
    title: 'Probabilidade & Estatística',
    badge: 'USP · ICMC',
    full: 'Fundamentos de Probabilidade e Estatística para Ciência de Dados',
    issuer: 'Universidade de São Paulo · ICMC',
    hours: '30h',
    credential: 'KPCP-CDSD-PLUH-7CE6',
    desc: 'Curso de Extensão Universitária no Instituto de Ciências Matemáticas e de Computação da USP. Fundamentos formais de probabilidade e estatística que sustentam toda inferência e análise quantitativa em comunicação.',
    skills: ['Probabilidade', 'Inferência', 'Estatística', 'Ciência de Dados'],
    verifyUrl: '/assets/cert-usp-probabilidade.pdf',
  },
];

export const SECTIONS = [
  { id: 'capa',         num: '01', label: 'CAPA' },
  { id: 'competencias', num: '02', label: 'PERFIL' },
  { id: 'projetos',     num: '03', label: 'PROJETOS' },
  { id: 'certificados', num: '04', label: 'CERTIFICADOS' },
  { id: 'depoimentos',  num: '05', label: 'DEPOIMENTOS' },
  { id: 'contato',      num: '06', label: 'CONTATO' },
];
